import "./globals.css";
import { CssBaseline } from "@mui/material";
import Header from "./components/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Crypto Orderbook</title>
      </head>
      <body
        style={{
          backgroundImage: "url(../stock.jpg)",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <CssBaseline />
        <Header />
        {children}
      </body>
    </html>
  );
}
